config/routes.rb
Rails.application.routes.draw do



  post '/rate' => 'rater#create', :as => 'rate'
  get 'main/index'
  get 'dashboards/seller'
  get 'dashboards/client'

  resources :products do
    resources :reservations , only: [:new,:create, :destroy]
    resources :comments

      member do
        put 'like', to: "products#like"
        put 'unlike', to: "products#unlike"
        get 'show-disponibility', to: "products#disponible"
      end

  end

  resources :notifications do

      collection do
        post :mark_as_read
      end

  end
  devise_for :users,path: '', path_names: { sign_in: 'login', sign_up: 'auth/Connect',sign_out: 'logout', edit: 'u/modify'}, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        confirmations: 'users/confirmations',
        passwords: 'users/passwords',
        omniauth_callbacks: 'users/omniauth_callbacks',
        invitations: 'users/invitations'

      }

  root 'products#index'
  match "*path", to: "application#index", via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :product_photo, ProductPhotoUploader


  belongs_to :traiteur, class_name: 'User', foreign_key: :traiteur_id
  has_many :comments, dependent: :destroy # if a product is deleted so are all of its comments
  has_many :reservations, dependent: :destroy
  has_many :clients , class_name: 'User',foreign_key: :product_id,:through => :reservations
  has_many :users , through: :comments
  has_many_attached :more_uploads
  has_many :notifications, foreign_key: :product_id ,dependent: :destroy


  enum status: [valable: 0  , non_valable: 1]
  #other
  acts_as_votable
  is_impressionable


  #validations
  validates :title , presence: true
  validates :description , presence: true

  validates :description, length: { maximum: 250, too_long: "%{count} caractéres en maximum" }
  validates :product_photo , presence: true
  enum category: [:Table , :Buffet ,:autres ]

  #Scopes

  #Nested attributes
  accepts_nested_attributes_for :reservations

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :like, :unlike,:disponible]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :like, :unlike]
  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :session_hash]
  include Pagy::Backend


  # GET /products
  # GET /products.json
  def index
    #@products = Product.all
     @q = Product.ransack(params[:q])
     @products = @q.result.includes(:traiteur,:comments)
      @pagy,@products =pagy(@products,items: 4)


  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @reservations = @product.reservations.all
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.traiteur_id = current_user.id
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.create(product_params)
    @product.traiteur_id = current_user.id

    respond_to do |format|
      if @product.save
        @product.is_borrowed = true
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def like
    @product.liked_by current_user
    #create notification
    Notification.create(recipient: @product.traiteur, actor: current_user, action: "liked", notifiable: @product,product: @product)
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout:false }
    end
  end

  def unlike
    @product.unliked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout:false }
    end
  end
  def disponible

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price,:traiteur_id,:product_photo,:category,more_uploads: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/views/products/_calendar.html.erb
          <div class="content">
            <div class="text-center">
                <div class="reservations-calendar">
                    <%= month_calendar events: reservations,remote: true  do |date,reservation|  %>

                   <%=  date %>
                 <% reservation.each do |res| %>
                      <% if res.present? %>
                        <div style="background-color: rgba(234,76,44,0.65)">
                          reserve
                        </div>


                      <% end %>

                </div>
                                  <% end %>
              </div>
                  <%end %>
                  </div>

app/views/products/_cantreserve.html.erb
<!-- Modal -->
<div class="modal fade" id="cantreserve" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        vous devez se connecter
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/products/_form.html.erb
<div class="form">
<%= simple_form_for @product, html: { multipart: true } do |f| %>
  <%= f.error_notification %>

  <div class="columns is-centered">
    <div class="column is-half">

      <% unless @product.product_photo_url.blank? %>
        <%= image_tag @product.product_photo_url(:thumb),class: "img-rounded" , id: "previewImage" %>
      <% end %>
      
      <output id="list"></output>
      <div id="drop_zone">Mettez l'image principale de la salle ici</div>
      <br />

      <%= f.input :product_photo, label: false, input_html: { class: "file-input", type: "file" }, wrapper: false, label_html: { class: "file-label" },placeholder: "votre fichier" %>

      <div class="form-group">
          <%= f.input :title , input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } ,placeholder: "Nom de la salle"%>
      </div>

      <div class="form-group">
          <%= f.input :description,as: :text, input_html: { class: "textarea"}, wrapper: false, label_html: { class: "label" },placeholder: "votre description" %>
      </div>

      <div class="form-group">
        <h4>Ajouter d'autres photos</h4>
        <%= f.file_field :more_uploads, multiple: true %>
      </div>

  <br>
      <div class="text-center">


      <div class="form-group">

        <div class="control">
          <%= f.submit "Ajouter", class:"btn btn-new btn-lg" %>
        </div>
      </div>
      </div>
    </div>
  </div>


<% end %>
</div>

app/views/products/_search.html.erb
  <div class="jumbotron jumbotron-fluid">


      <p class="lead">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= search_form_for @q ,validate: true do |f| %>
          <div class="input-group" id="adv-search">
            <%= f.search_field :title_or_description_cont ,class: "form-control",placeholder: "QUE CHERCHEZ-VOUS ?"%>

            <div class="input-group-btn">
              <div class="btn-group" role="group">
                <div class="dropdown dropdown-lg">
                  <button type="button" class="btn  dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></button>
                  <div class="dropdown-menu dropdown-menu-right" role="menu">
                    <form class="form-horizontal" role="form">
                      <div class="form-group">
                        <label for="filter">Filtrer par:</label>

                      </div>

                      <div class="form-group">

                        <%= f.search_field :traiteur_name_cont,class: "form-control",autofocus: true ,
                                           input_html: { autocomplete: "name" },placeholder: "nom du traiteur" %>
                      </div>
                      <br>
                      <br>

                      <br>
                      <br>
                      <div class="form-group">

                        <%= f.search_field :price_gteq ,class: "form-control",autofocus: true ,
                            placeholder: "prix min" %>
                        <br>
                        <br>
                        à
                        <%=f.search_field :price_lteq,class: "form-control",autofocus: true ,
                                         placeholder: "prix max" %>
                      </div>
                      <br>
                      <br>
                     <div class="form-group">
                       <%= f.submit "Recherche Avancée" ,class: "btn btn-search-submit" do %>
                         <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                       <% end %>


                     </div>

                    </form>
                  </div>
                </div>
                <%= f.submit "Rechercher", class: "btn btn-search-submit" %>


              </div>
            </div>
          </div>
        </div>
            <% end %>
      </div>
    </div>
  </div>

app/views/products/_search_ad.html.erb
<% if !user_signed_in? %>
<div class="jumbotron " style="background-color: white">

  <div class="container">
  <div class="text-center">


      <div class="col-md-12">
        <%= search_form_for @q ,validate: true do |f| %>
          <form class="form-horizontal">


      <div class="input-group-lg">
        <div class="row">
          <div class="col-xs-4">
            <div class="form-group">
              <input type="text" class="form-control  " placeholder="Que recherchez-vous ??">
            </div>

          </div>
          <div class="col-xs-4">
            <div class="form-group">
              <input type="text" class="form-control " placeholder="où">
            </div>

          </div>
          <div class="col-xs-4">
            <div class="form-group">
              <button type="button" class="btn btn-search-submit  ">Rechercher</button>
            </div>

          </div>

        </div>
      </div>


          </form>


      </div>
        <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/products/edit.html.erb
<div class="container">

  <div class="box">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
          <%- model_class = Product -%>
              <div class="page-header">
                  <h1>Modifier le produit</h1>
              </div>
          <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<%#= render 'products/search_ad' %>


  <%= render 'products/search' %>


  <section class="container">
    <div class="row">
          <% @products.each  do |pr| %>

            <div class="col-md-3 col-sm-6">
              <div class="product-grid">
                <%= link_to pr, class: "product" do %>
                <div class="product-image">
                  <%= image_tag(pr.product_photo.url(:thumb),class: " pic-1 img-rounded") %>
                 <%= link_to pr,class: "More-about", 'data-tip' => "More about.." do %>
                    <i class="fas fa-info-circle"></i>
                    <% end %>
                </div>
                <div class="product-content">
                  <h3 class="title">
                    <%=  pr.title %>
                  </h3>
                  <!--
                  <div class="price"><#%= pr.price %> DH</div>
                  !-->
                  <h5> :<%= time_ago_in_words(pr.created_at) %></h5>
                  <ul class="social">
                    <li><%= link_to pr, 'data-tip' => "view"  do %>
                        <span class="icon"><i class="fa fa-eye" ></i></span>
                        <span class="vote_count"><%= pr.impressionist_count %></span>
                      <% end %>
                    </li>
                <% end %>
                    <li>
                      <% if user_signed_in? %>

                        <% if current_user.liked? pr %>
                          <%= link_to unlike_product_path(pr), 'data-tip' => "unlike",method: :put, :class => "unlike_product" do %>
                            <span class="icon"><i class="fa fa-heart text-danger"></i></span>
                            <span class="vote_count"><%= pr.get_likes.size %></span>
                          <% end %>
                        <% else %>
                          <%= link_to like_product_path(pr), 'data-tip' => "like",method: :put, :class => "like_product" do %>
                            <span class="icon"><i class="fa fa-heart"></i></span>
                            <span class="vote_count"><%= pr.get_likes.size %></span>
                          <% end %>
                        <% end %>
                      <% else %>
                        <%= link_to like_product_path(pr),'data-tip' => "like", method: :put, :class => "like_product" do %>
                          <span class="icon"><i class="fa fa-heart"></i></span>
                          <span class="vote_count"><%= pr.get_likes.size %></span>
                        <% end %>
                      <% end %>
                    </li>


                    <li><%= link_to pr, 'data-tip' => "comment" do %>
                        <span class="icon"><i class="fa fa-comment"></i></span>
                        <%= pr.comments.count %>
                      <% end %>

                    </li>
                  </ul>
                </div>

              </div>




        <div class="user-data">
          <div class="user-thumb">
            <%= image_tag(avatar_url(pr.traiteur), alt: pr.traiteur.name,class: "img-circle ",style: "max-width: 100%;height:30px;display:inline-block;border-radius:100%;")  %>
          </div>
          <div class="user-name"><%= pr.traiteur.name %></div>
        </div>
            </div>
      <% end %>
    </div>
  </section>
      <div class="text-center">
          <%= pagy_nav_bootstrap(@pagy).html_safe %>
      </div>

app/views/products/new.html.erb
<div class="container">

  <div class="box">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">


    <%- model_class = Product -%>
          <div class="page-header">
            <%= sanitize image_tag "wedding" ,alt: "wedding" ,width: "100%",height: "100%",class: "img-fluid "%>
          </div>
              <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col">
        <h1 class="title is-3"><%= @product.title %></h1>

        <span class="by has-text-grey-light">De</span>
        <div class="user-name has-text-weight-bold"><%= @product.traiteur.name %></div>
        <div class="product-time"><span class="has-text-grey-light"></span><span class="has-text-weight-semibold">
					<%= @product.created_at.strftime"créé le %m/%d/%Y à %I:%M%p" %>
				</span>
          <% if user_signed_in? %>
            <% if !current_user.is_seller? %>
          <div class="btn btn-disponibiliy btn-sm" data-toggle="modal" data-target="#show-disponibilty">
            <%= link_to show_disponibility_product_path(@product),remote: true  do%>
            Disponibilité ?
            <% end %>
          </div>

            <% end %>
            <% end %>
        </div>

      </div>
    </div>
    <div class="row">

      <div class="col">
        <div class="product-container">
            <%= image_tag @product.product_photo.url(:thumb),class: "img-rounded" unless @product.product_photo.blank? %>
            <%  (0...@product.more_uploads.count).each do |image| %>
                  <%= image_tag(@product.more_uploads[image],class: "img-rounded")%>
            <% end %>
        </div>
        <br>
      </div>
    </div>

    <div class="row">
        <div class="col-md-1">
            <% if user_signed_in? && (current_user.id == @product.traiteur_id) %>
              <div class="btn-group-sm">
                <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-edit" %>
                <%= link_to 'Delete', product_path(@product), class: "btn btn-delete", method: :delete, data: { confirm: 'Are you sure you want to delete this product?'} %>
              </div>
            <% end %>
        </div>

        </div>

    </br>
        <div class="row">


          <div class="content">
            <div class="panel panel-default">
              <div class="panel-body small">
               <p class="description" ><%= @product.description %></p>
              </div>
            </div>

          </div>

        <section class="comments">
          <h3 class="subtitle is-5"><%= pluralize(@product.comments.count, 'Comment') %></h3>
          <%= render @product.comments %>
          <hr/>
          <% if user_signed_in? %>
            <div class="comment-form">
              <h3 class="text-justify">Laisser un commentaire :</h3>
              <%= render 'comments/form' %>
            </div>
          <% else %>
            <div class="content"><%= link_to 'Sign in', new_user_session_path ,:class => "btn btn-primary"%> to leave a comment.</div>
          <% end %>
        </section>
        </div>


    <div class="row">
        <div class="col-md-1">
          <div class="panel-default">
              <div class="panel-body">
                </br>
                </br>
              </div>
          </div>
        </div>
      </div>



<% if user_signed_in? %>
    <% if !current_user.is_seller %>
<div class="footer">

  <div class="footer_contents">

    <div class="navbar navbar-default navbar-fixed-bottom">
      <div class="container">
        <div class="center">
          <div data-toggle="modal" data-target="#new-reservation" class="navbar-btn btn-reservation btn pull-right" >
        <%#= link_to  new_product_reservation_path(@product),:class => "navbar-btn btn-reservation btn pull-right" ,remote: true do %>
                  Demande de Réservation
          <%#end %>
          </div>
        </div>
      </div>
    </div>
  </div>

    <% end %>
</div>
<% else %>
  <div class="footer">

    <div class="footer_contents">

      <div class="navbar navbar-default navbar-fixed-bottom">
        <div class="container">
  <!-- Button trigger modal -->

  <%= link_to "Demande de Réservation",'#cant-reserve','data-toggle' => 'modal',:class => "navbar-btn btn-reservation btn pull-right" %>






<% end %>

</div>
</div>
</div>
</div>

<!-- Modal -->
<div class="modal fade" id="cant-reserve" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="text-center">
          <%= sanitize image_tag "lighthouse" ,alt: "lighthouse" ,width: "50%",height: "50%",class: "img-fluid " %>
          <h4>vous devez se connecter ou s'inscrire si vous n'avez pas de compte </h4>
        </div>


      </div>
      <div class="modal-footer">
        <%= link_to "Se Connecter" , new_user_session_path,:class => "btn btn-reserve-signin" %>
        <%= link_to "S'inscrire" , new_user_registration_path,:class => "btn btn-reserve-signup" %>
      </div>
    </div>
  </div>
</div>
<!-- fin Modal -->

<!-- Modal -->
  <div class="modal fade" id="new-reservation" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog img-rounded" style="background-color: white; max-width: 1000px;">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="lineModalLabel" class="title is-6"> <%= @product.title %></h3>
      </div>
      <div class="modal-body">
            <%= render 'reservations/form'   %>
        </div>
      </div>
    </div>
  </div>

<!-- fin modal -->


  <!-- Modal -->
  <div class="modal fade" id="show-disponibilty" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog img-rounded" style="background-color: white; max-width: 1000px;">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="lineModalLabel" class="title is-8"></h3>
      </div>
      <div class="modal-body">


          <div class="text-center">
            <div id="reservations_calendar">
              <%= render partial: "calendar", locals: {reservations: @reservations} %>
            </div>
          </div>

      </div>
    </div>
  </div>
  <!-- fin modal -->

app/views/products/show.js.erb
$("#reservations_calendars").html("<%= escape_javascript render(partial: "calendar", locals: {reservations: @reservations}) %>");