config/routes.rb
Rails.application.routes.draw do



  post '/rate' => 'rater#create', :as => 'rate'
  get 'main/index'
  get 'dashboards/seller'
  get 'dashboards/client'

  resources :products do
    resources :reservations , only: [:new,:create, :destroy]
    resources :comments

      member do
        put 'like', to: "products#like"
        put 'unlike', to: "products#unlike"
        get 'show-disponibility', to: "products#disponible"
      end

  end

  resources :notifications do

      collection do
        post :mark_as_read
      end

  end
  devise_for :users,path: '', path_names: { sign_in: 'login', sign_up: 'auth/Connect',sign_out: 'logout', edit: 'u/modify'}, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        confirmations: 'users/confirmations',
        passwords: 'users/passwords',
        omniauth_callbacks: 'users/omniauth_callbacks',
        invitations: 'users/invitations'

      }

  root 'products#index'
  match "*path", to: "application#index", via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Untitled</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>

    <nav class=" navbar navbar-expand-lg navbar-light  navbar-farah "  >
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button style="background-color:white;border-radius: 200px;border-color: #3c16ff" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span style="color: #ea1b1a" class="navbar-toggler-icon">Menu</span>

      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class=" nav navbar-nav navbar-left">
        <li class="nav-item"><%= link_to "BRAND",root_path %></li>
        <li class="nav-item" ><a href="#">Pricing</a></li>
        <li class="nav-item"><a href="#">Qui sommes-nous ?</a></li>


      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.is_seller? %>
            <li class="nav-item"><%= link_to "Calendrier" ,dashboards_seller_path, :class => "btn btn-dashboard-seller"%></li>
            <li class="nav-item"><%= link_to new_product_path,'data-tip' => "Nouveau",:class => "btn btn-new-product" do%>
                Nouveau <span ><i class="fas fa-plus "></i></span>
            <% end %>

            </li>
            <li class="nav-item " data-behavior="notifications" data-notifications='<%= render template: "notifications/index", formats: [:json] %>'>
              <a class="m-2 dropdown-toggle nav-link" href="#" role="button" data-behavior="notifications-link" id="dropdownnotifications" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span><i class="far fa-bell fa-lg" ><span class="badge badge-danger" data-behavior="unread-count"></span></i></span>
              </a>

              <ul class="dropdown-menu dropdown-menu-notif" aria-labelledby="dropdownnotifications" data-behavior="notification-items">
                <!--
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
                -->
              </ul>
            </li>
              <li class="nav-item">

                <%= link_to  "#",:role => "presentation", :class =>"dropdown",'data-toggle' => 'dropdown' do%>
                  <%= image_tag avatar_url(current_user),class: "img-circle ",style: "max-width: 200%;height:50px;display:inline-block;border-radius:100%;"  %>
                  <span class="caret"></span>

                <%end %>
                <ul class="dropdown-menu">
                 <li><%= link_to "Modifier le profil",edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Déconnexion",destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>

              <li class="nav-item"></li>
            <%else %>
            <li class="nav-item"><%= link_to "",:class => "btn btn-favorites" do %>
                <span>Favoris</span>
                <% end %>
                </li>

            <li class="nav-item"><%= link_to "inviter vos amis",new_user_invitation_path,:class => "btn btn-invitation" %>
            <li class="nav-item " data-behavior="notifications" data-notifications='<%= render template: "notifications/index", formats: [:json] %>'>
              <a class=" m-2 dropdown-toggle nav-link" href="#" role="button" data-behavior="notifications-link" id="dropdownnotifications" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                <span><i class="far fa-bell fa-lg" >
                  <span class="badge badge-danger" data-behavior="unread-count"></span>
                </i></span>
              </a>
              <ul class="dropdown-menu dropdown-menu-notif" aria-labelledby="dropdownnotifications" data-behavior="notification-items">
                <!--
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
                -->
              </ul>
                </li>
            <li class="nav-item">

              <%= link_to  "#",:role => "presentation", :class =>"dropdown",'data-toggle' => 'dropdown' do%>
                <%= image_tag avatar_url(current_user),class: "img-circle ",style: "max-width: 100%;height:20px;display:inline-block;border-radius:100%;"  %>
                <span class="caret"></span>

              <%end %>
              <ul class="dropdown-menu">
                <li><%= link_to "Modifier le profil",edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Déconnexion",destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        <%else %>

          <li class="nav-item"><%=link_to "Se Connecter",new_user_session_path ,:class =>"nav-link-signin "%></li>
          <li class="nav-item"><%=link_to "S'inscrire",new_user_registration_path,:class =>"nav-link-signup"%></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <%= render 'layouts/messages' %>
  <%= yield %>

</div>

  </body>
</html>